version: '3.3'
services:
  webserver:
    image: "wordpress:5.1.1-php7.2-apache"
    restart: always
    ports:
      - "8081:80"
    networks:
      - dock-net
    environment:
      WORDPRESS_DB_HOST: mysqldb
      WORDPRESS_DB_USER: wp-user
      WORDPRESS_DB_PASSWORD: wp@123
      WORDPRESS_DB_NAME: wp-db


  mysqldb:
    image: "mysql:5.7.26"
    restart: always
    environment:
      MYSQL_DATABASE: wp-db
      MYSQL_USER: wp-user
      MYSQL_PASSWORD: wp@123
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - dock-net
volumes:
    db-data:

networks:
    dock-net:
